package com.example.customkeyboard.Keyboard_Engine

/** Owns the keyboard engine: layouts, key handling, and input modes. */
interface KeyboardEngine {

    /** Writes a single character/key event generated by a tap. */
    fun onKeyTap(keyCode: Int): Boolean

    /** Handles a long-press action, e.g. secondary symbols or accents. */
    fun onKeyLongPress(keyCode: Int): Boolean

    /** Starts a tap-typing session (tapping without sliding). */
    fun startTapTyping()

    /** Starts a swipe/glide typing session. */
    fun startGlideTyping()

    /** Applies automatic correction to recognized gestures. */
    fun autoCorrect(input: String): String

    /** Switches the active keyboard layout (QWERTY, symbols, numeric). */
    fun setLayout(layout: KeyboardLayout)

    enum class KeyboardLayout { QWERTY, SYMBOLS, NUMERIC }
}